#! /bin/bash
set -e

# https://github.com/kc910521
# test in root,  ubuntu 16.04
# refine app usage log from sys log history

# backup map file

CTIME=$(date +%Y-%m)

BK_FNAME=$(whoami)_${CTIME}.his.bk

FILE_PATH=~/.bash_history

#set +x
echo bk name is ${BK_FNAME}

EXP_IGNORE_HEAD='ls|cd|grep|history|vi|kill|ps|tail|less|more|iptables|rm'

if [ ! -f "./${BK_FNAME}" ];then
  echo ${BK_FNAME}:create...
  cat $FILE_PATH | sort -u | egrep -v "(^($EXP_IGNORE_HEAD))|(^sudo\s+($EXP_IGNORE_HEAD))" > ./$BK_FNAME
  echo saved 
else
  echo merge both
  cat $FILE_PATH ./$BK_FNAME | sort -u | egrep -v "(^($EXP_IGNORE_HEAD))|(^sudo\s+($EXP_IGNORE_HEAD))" > ./$BK_FNAME
fi

#set -x
