#! /bin/bash
set -e

# https://github.com/kc910521
# test in root,  ubuntu 16.04
# refine app usage log from sys log history

# backup map file

CTIME=$(date +%Y-%m)

BK_FNAME=$(whoami)_${CTIME}.his.bk

FILE_PATH=~/.bash_history

TEMP_HEAD=

# never add any echo in the func 
function PARAMS_EQ_CMD(){
  if [ $# -gt 1 ];then
    idx=0
    fstParam=$1
    for i in "$@"; do
      if [ $idx -gt 0 ];then
        if [ $i == "$fstParam" ];then
	  echo 1;
	  return 0;
	fi
      fi
      idx+=1
    done
  else
    echo 1;
    return 0;
    #true
  fi
  # default as return false
  echo 0;
  return 0;
}


#data display
function MK_OUTPUT_LINE(){
 :<<! 
  result=$(PARAMS_EQ_CMD df $*);
  echo "godaddy$?"
  echo "${result}ddddd"
!

  while read LINE
  do
    ORG_LINE=$LINE
    TH_TMP=$(echo $LINE| sed 's/ .*$//')
    result=1
    if [ $# -gt 0 ];then
      result=$(PARAMS_EQ_CMD ${TH_TMP} $*)
    else
      result=1
    fi
    #echo TH_TMP
    if [ ${result} -gt 0 ];then
      if [ "${TEMP_HEAD}" == "${TH_TMP}"  ];then
        echo ''
      else
         TEMP_HEAD=$TH_TMP
         echo ======================================================================\| $TEMP_HEAD \|==========================================
      fi
      echo $LINE
    fi
    #echo "ssss"
  done < $BK_FNAME
}



#set +x
echo bk name is ${BK_FNAME}

EXP_IGNORE_HEAD='ls|cd|grep|history|vi|kill|ps|tail|less|more|iptables|rm'

if [ ! -f "./${BK_FNAME}" ];then
  echo ${BK_FNAME}:create...
  cat $FILE_PATH | sort -u | egrep -v "(^($EXP_IGNORE_HEAD))|(^sudo\s+($EXP_IGNORE_HEAD))" > ./$BK_FNAME
  echo saved 
else
  echo merge both
  cat $FILE_PATH ./$BK_FNAME | sort -u | egrep -v "(^($EXP_IGNORE_HEAD))|(^sudo\s+($EXP_IGNORE_HEAD))" > ./$BK_FNAME
fi

MK_OUTPUT_LINE $*;


#set -x
